- hosts: all
  gather_facts: no
  become: False
  tasks:

      - shell: cd /tech/installers/thinkbox/10.3.2/ ; ./DeadlineClient-10.3.2.1-linux-x64-installer.run --mode unattended --connectiontype Remote --proxyrootdir 10.1.64.94:4433 --dbsslcertificate /tech/apps/thinkbox/10.3.2/Deadline10/certs/Deadline10RemoteClient.pfx --dbsslpassword s3cr3tp@$$ --daemonuser dna  --slavestartup true --launcherdaemon true ;systemctl daemon-reload

        register: out

      - debug:
         msg: '{{ out.stdout_lines }}'
