---
- name: package depolyment  
  hosts: all
  become: no
  tasks:
    - name: shotcut package 
      ansible.builtin.shell: |
        unset HTTP_PROXY no_proxy https_proxy HTTPS_PROXY FTP_PROXY ftp_proxy http_proxy NO_PROXY ; flatpak install -y flathub org.shotcut.Shotcut
      register: command1_output

    - name:  who
      ansible.builtin.shell: |
        who
      register: command2_output

    - name: Debug all command outputs at the end
      ansible.builtin.debug:
        msg:
          - "Command 1 Output: {{ command1_output.stdout }}"
          - "Command 2 Output: {{ command2_output.stdout }}"
