---
- name: packeage update 
  hosts: all
  become: no
  tasks:
    - name: shohtcut package 
      ansible.builtin.shell: |
        unset HTTP_PROXY no_proxy https_proxy HTTPS_PROXYFTP_PROXY ftp_proxy http_proxy NO_PROXY ; flatpak install -y flathub org.shotcut.Shotcut ; flatpak run org.shotcut.Shotcut
      register: command1_output

    - name: blender 
      ansible.builtin.shell: |
        cp -r /apps/sreelinux/blender.desktop /usr/share/applications/
      register: command2_output

    - name: Debug all command outputs at the end
      ansible.builtin.debug:
        msg:
          - "Command 1 Output: {{ command1_output.stdout }}"
          - "Command 2 Output: {{ command2_output.stdout }}"
