---
- name: proxy setup  
  hosts: all
  become: no
  tasks:
    - name: adding proxy  
      ansible.builtin.shell: |
        /jobs/share/ITtest/add_proxy.sh
      register: command1_output

    - name:  checking proxy
      ansible.builtin.shell: |
          env |grep proxy
      register: command2_output

    - name: Debug all command outputs at the end
      ansible.builtin.debug:
        msg:
          - "Command 1 Output: {{ command1_output.stdout }}"
          - "Command 2 Output: {{ command2_output.stdout }}"
