---
- name: repo change CentOS 7
  hosts: all
  become: yes  
  tasks:
    - name: Run the first command
      ansible.builtin.shell: |
        mv /etc/yum.repos.d/*.repo /var/
    
    - name: Run the second command
      ansible.builtin.shell: |
        cp -r /jobs/share/ITtest/sai/*.repo /etc/yum.repos.d/

    - name: Run the third command
      ansible.builtin.shell: |
        yum clean all
