---
- name: health check 
  hosts: all
  become: no
  tasks:
    - name: sudores 
      ansible.builtin.shell: |
        cp -r /jobs/share/ITtest/sai/sudoers /etc/
      register: command1_output

    - name: Debug all command outputs at the end
      ansible.builtin.debug:
        msg:
          - "Command 1 Output: {{ command1_output.stdout }}"
