---
- name: Detect OS type and write to a file
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check if the system is Linux
      set_fact:
        os_type: "Linux"
      when: ansible_facts['os_family'] == 'Linux'

    - name: Check if the system is Windows
      set_fact:
        os_type: "Windows"
      when: ansible_facts['os_family'] == 'Windows'

    - name: Write the result to a file
      copy:
        dest: "/tmp/os_detected.txt"
        content: |
          System Information:
          Host: {{ inventory_hostname }}
          OS Type: {{ os_type }}
        append: yes
      delegate_to: localhost
