---
- name: Find the user logged in via PowerShell
  hosts: all
  tasks:
    - name: Copy PowerShell script to remote machine
      ansible.windows.win_copy:
        src: /root/find.ps1
        dest: C:\temp\find_logged_in_user.ps1

    - name: Execute the PowerShell script
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\temp\find_logged_in_user.ps1
      register: result

    - name: Show the output from the script
      debug:
        msg: "{{ result.stdout }}"
